"""crear tablas iniciales

Revision ID: ae435955cf6f
Revises: 0d93c2fa5acf
Create Date: 2026-09-11 07:05:29.173841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae435955cf6f'
down_revision: Union[str, Sequence[str], None] = '0d93c2fa5acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convocatorias', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convocatorias', 'time_created')
    # ### end Alembic commands ###
